

```{r}
dds <- DESeqDataSetFromMatrix(countData = raw_counts.HIP,
                              colData =  sample_table.HIP, 
                              design = ~Sex)
dds <- DESeq(dds)
```

```{r}
res_sex <- results(dds,
               contrast = c('Sex',"F","M"))
res_sex <- as.data.frame(res_sex)
res_sex <- res_sex[!is.na(res_sex$padj),]
```


```{r}
res_sex$padj[res_sex$padj < 10e-20] <- 10e-20

keyvals <- ifelse(
  res_sex$log2FoldChange < -log2(1.2) & res_sex$padj < 0.05, 'blue',
    ifelse(res_sex$log2FoldChange > log2(1.2) & res_sex$padj < 0.05, 'red',
      'black'))
names(keyvals)[keyvals == 'red'] <- 'Upregulated'
names(keyvals)[keyvals == 'black'] <- 'N.S.'
names(keyvals)[keyvals == 'blue'] <- 'Downregulated'


EnhancedVolcano(res_sex,
    lab = rownames(res_sex),
    selectLab = rownames(res_sex)[which(names(keyvals) %in% c('Upregulated', 'Downregulated'))],
    colCustom = keyvals,
    x = 'log2FoldChange',
    y = 'padj',
    ylab = bquote(~-Log[10]~ 'Adjusted p'),
    pCutoff = 0.05,
    FCcutoff = log2(1.2),
    subtitle = "",
    title = bquote("Male vs Female"),
    legendPosition = 'none',
    colAlpha = 1, caption = ""
    ) +
    ggplot2::coord_cartesian(xlim=c(-15, 15),ylim = c(0,20)) +
    ggplot2::scale_x_continuous(
      breaks=c(-10,-5,-2,2,5,10)) +
  theme(plot.title = element_text(hjust = 0.5, size = 20),
        panel.grid.minor = element_blank(),
        panel.grid.major = element_blank(),
        panel.border = element_rect(size = 2,fill = NA))
```


